### ISSUE TITLE
Improve `getSequenceSizes()` performance

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/twobit-js#4]
Maybe instead of using dnaSize in each sequence record, we could infer the sizes from the offsets? Or maybe some other way?

http://genome.ucsc.edu/FAQ/FAQformat.html#format7

**Comment by cmdcolin** [comment]
Looks like we can't get sizes from offsets because the block for the sequence record I think is variable size

**Comment by cmdcolin** [comment]
Maybe the question is: do we need the list of all sequence sizes up front. Commonly the answer has been yes to enable things like "sort by length" but if sort by length isn't enabled for example, it might not be necessary

**Comment by cmdcolin** [comment]
in jbrowse 2 we solved this somewhat by supplying a chrom.sizes alongside a twobit file so we don't need to use getSequenceSizes
