### ISSUE TITLE
wheat.2bit test data is a symlink

### ISSUE THREAD

**Issue by jrobinso** [GMOD/twobit-js#43]
Hi all, great project.  I am looking to use it in igv.js.   Just letting you know what "wheat.2bit" is a soft link to a local file on Robert's computer.

**Comment by cmdcolin** [comment]
probably because wheat is a very large file to test against :) we could probably consider removing it since it's a bit unused, @gmod/cram had some similar symlinks that were recently removed

**Comment by cmdcolin** [comment]
readme now has docs for module usage...had been lost at some point but now restored

**Comment by cmdcolin** [comment]
close for now. the usage of binary-parser (CSP violation) also removed from here too now
